# Generated by Django 3.2.2 on 2021-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='name',
            field=models.CharField(default=20200101, max_length=250),
            preserve_default=False,
        ),
    ]
