# Generated by Django 3.2.2 on 2021-05-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import risks_mitigations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('TECH', 'Tech'), ('OPERATION', 'Operation'), ('COMMERCIAL', 'Commercial'), ('LEGAL', 'Legal'), ('MARKETING', 'Marketing'), ('FIANCE', 'Finance'), ('CX', 'CX'), ('BD', 'BD'), ('HR', 'HR')], default='TECH', max_length=100)),
                ('riskname', models.CharField(max_length=300)),
                ('risknameCause', models.CharField(max_length=500)),
                ('riksEffect', models.CharField(max_length=500)),
                ('inherent', models.IntegerField(default=1, validators=[risks_mitigations.models.validate_number])),
                ('recidual', models.IntegerField(default=1, validators=[risks_mitigations.models.validate_number])),
                ('target', models.IntegerField(default=1, validators=[risks_mitigations.models.validate_number])),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riskcreate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=250)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks_mitigations.risk')),
            ],
        ),
    ]
